# Generated by Django 4.2 on 2025-09-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='boost',
            field=models.BooleanField(default=False),
        ),
    ]
