# Generated by Django 4.2 on 2025-09-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_chat_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='earned_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
